FROM python:3.10-slim

WORKDIR /app

COPY ./app/dashboard /app
COPY requirements.txt /app

RUN pip install --no-cache-dir -r requirements.txt

CMD ["streamlit", "run", "forex_dashboard.py", "--server.port=8501", "--server.address=0.0.0.0"]
